=== endeavourhealth/EDS/src/external-components/EmisWebPollerService/Endeavour.EmisWebPollerService/Configuration/Configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Endeavour.EmisWebPollerService">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Configuration" type="Configuration">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Configuration">
    <xs:sequence>
      <xs:element name="EndeavourServiceEndpoint" type="NonEmptyString"/>
      <xs:element name="ServiceThreadSleepMilliseconds" type="xs:int"/>
      <xs:element name="EmisWebCdb" type="xs:int"/>
      <xs:element name="EmisWebIPAddress" type="NonEmptyString"/>
      <xs:element name="PartnerApiKey" type="NonEmptyString"/>
      <xs:element name="PartnerApiUserName" type="NonEmptyString"/>
      <xs:element name="PartnerApiPassword" type="NonEmptyString"/>
      <xs:element name="IsPartnerApiPasswordEncrypted" type="xs:boolean"/>
      <xs:element name="SynchronizationFrequencyMinutes" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
	<xs:simpleType name="NonEmptyString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:pattern value=".*[^\s].*"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== endeavourhealth/EDS/src/external-components/EmisWebPollerService/Endeavour.EmisWebPollerService/Configuration/Configuration.xml
<?xml version="1.0" encoding="utf-8"?>
<Endeavour.EmisWebPollerService xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="Configuration.xsd">
  <Configuration>
    
		<!-- Endeavour endpoint for receiving patient records -->
		<EndeavourServiceEndpoint>http://127.0.0.1:8080/api/v0.1/Bulk/Patient</EndeavourServiceEndpoint>
    
		<!-- Number of minutes for Windows service thread to sleep for after completing one cycle -->
		<!-- Note: setting this too high will lead in the service becoming unresponsive -->
		<ServiceThreadSleepMilliseconds>1000</ServiceThreadSleepMilliseconds>
    
		<!-- EMIS Web CDB number for the site this is running at -->
		<EmisWebCdb>50002</EmisWebCdb>
    
		<!-- IP address of EMIS' EMAS server.  This is provided by EMIS -->
		<EmisWebIPAddress>127.0.0.1</EmisWebIPAddress>
    
		<!-- Endeavour Health Partner API key.  Also provided by EMIS. -->
		<PartnerApiKey>417fd2ff-aeba-46e7-82b6-9ceb496dcfdf</PartnerApiKey>
    
		<!-- Partner API username.  This is specific to the site being installed at. -->
		<PartnerApiUserName>emistest</PartnerApiUserName>
    
		<!-- Encrypted partner API password.  This is specific to the site being installed at. -->
		<!-- Note: this may be different from the same as the client login password -->
		<PartnerApiPassword>Emis1234</PartnerApiPassword>
    
		<!-- Whether the PartnerApiPassword is encrypted or not -->
		<!-- If the password is not encrypted, set the value to false, and the poller will encrypt it on first run -->
		<IsPartnerApiPasswordEncrypted>false</IsPartnerApiPasswordEncrypted>
    
		<!-- Partner API password.  This is specific to the site being installed at. -->
		<SynchronizationFrequencyMinutes>1</SynchronizationFrequencyMinutes>
    
	</Configuration>
</Endeavour.EmisWebPollerService>
